server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  application:
    name: spring-blog
  datasource:
    url: jdbc:mysql://localhost:3306/spring-blog
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: 350999b1feed6d3f51f110e7ab29e603e75f1a2cdaf7e96af3bb2ad51f24d917
  valid-duration: 10
  refreshable-duration: 20